- jeongmin/Chapter1.md
저자가 그리는 큰 그림을 엿보고 온 느낌이 들었습니다. 
종종 자세히 알지 못하는 개념들을 만나, 클로드와 재미있게 질의 응답을 하면서 얻어가는 정보가 꽤 있었습니다. 유의미한 공부를 했다고 생각합니다.
저는 useState외에 useReducer는 실무에서 거의 쓰지 않는 편인데요, 리액트 코드를 뜯어보니 내부에서 상태를 관리하는 주요한 함수로는 useState보다 useReducer를 위주로 사용하고 있다고 보였습니다.
만약 외부 상태관리 라이브러리를 이용할 수 없는 상황에서 useReducer를 잘 사용하면 꽤나 유용 할 것 같다는 생각이 들었는데요, 다른 분들은 실무에서 useReducer를 어떻게 사용하고 계시는지 궁금합니다.
> [Week01] 성정민

- moonha/chapter-01.md
책의 제목인 '마이크로 상태 관리'가 무엇인지 1장을 읽으니 알 수 있게 되었고
`useState`, `useReducer`를 코드로 비교하면서 되지어 볼 수 있어서 좋았습니다.
`useReducer`는 평소에 잘 활용을 못하고 있었는데.. 어떻게 잘 활용 할 수 있을지 좀 더 찾아봐야겠습니다.
이번 장을 읽으면서 같이 얘기 나눠보면 좋을 것 같다는 주제가 있는데...
- useReducer 자주 사용하시는 분들은 어떤 기준으로 사용하시는지 궁금합니다. 나만의 꿀팁(?)이 있으면 공유해주시면 감사할 것 같아요!
- 리액트 개발하실 때 훅으로 로직과 렌더링 부분을 나누시는 편인지, 나눈다면 어느 정도 수준까지 나누시는지 궁금합니다.
> [Week01] 박문하

- mogyeong/chapter01.md
- '베일아웃' 이라는 개념에 처음으로 알게 되었고, 리액트에서 베일아웃이 작동되는 원리를 심층해서 공부해보면 좋을 것 같다.
- 전역 상태 관리를 위해 useState, useReducer만을 이용하는게 최선책은 아니겠지만 1장이다보니 입문용 hook으로 설명을 들어 쉽게 이해할 수 있었던 것 같다.
1장에서 나온 내용 외에 전역 상태 관리하는 방법을 알아볼 필요를 느꼈다.
- 평소에 'useReducer를 사용해야겠다' 고 느낀적이 잘 없었는데, 1장 내용을 읽으면서도 useReducer를 더 잘 사용해야겠다는 느낌을 확 와닿지는 못했다. 실제로 잘 활용한 사례가 필요할 듯 하다.
> [Week01] 김모경

- moonha/chapter-02.md
본격적인 내용에 들어가기 전에, 알고 있던 내용을 다시 한 번 정리할 수 있는 챕터였습니다. 
컴포넌트를 props로 전달하는 것은 자연스럽게 해왔지만, 이를 내용 끌어올리기(Lifting Content Up)라는 개념으로 다시 정리하고, 리렌더링 부분까지 짚어주어 좋았습니다.
> [Week02] 박문하

- mogyeong/chapter02.md
책의 초반부라 그런지 1, 2장은 내용이 많이 축약되어 있고 워밍업같은 느낌으로 느껴졌습니다.
이번 2장은 지역 상태와 전역 상태에 대한 효과적 사용법에 대해 알기 쉽게 설명이 되어져있었습니다.
크게 거슬리거나 의문이 드는 내용은 없었고, 그 만큼 개괄적인 내용이었습니다.
평소에 전역 상태를 잘 다루는 데에는 많이 숙련되지 않았고, 개념이나 사용법만 알고 있었는데 “언제 전역 상태를 사용해야하는지” 에 대해 책에서 짚어줘서 좋았습니다.
> [Week02] 김모경

- wonjun/chapter-2.md
- 일 하면서 스터디 하는 모든 분들을 존경합니다
- 이것도 몸으로 배운게 대부분이라서 뭔가 용어 정리를 한 기분
> [Week02] 이원준 

- jeongmin/Chapter1.md
- jeongmin/Chapter2.md
기술 관련 책을 읽다보면 종종 실무에서 두들겨 맞으면서 익혔던 개념을 명확한 단어로 친절하게 이해시켜 주는 경험을 할 때가 있습니다. 
이번에도 추상적으로 알고 있던 체득식 개념을 구체적인 이론으로 정리 할 수 있어서 좋았습니다. 
(순수 함수 컴포넌트 / 내용 끌어올리기 / 상태 끌어올리기 등)
> [Week02] 성정민

- jaewon/Chapter.md
1장과 2장, 그리고 3장의 대부분의 내용들은 React의 API/Hook 사용법이 주를 이루는 것 같습니다. 사실 내용적으론 크게 재미없는 파트라 생각이 드는데, 글에 녹아져있는 저자의 철학이 재밌네요. [저자의 블로그](https://blog.axlight.com/)입니다. 시간나실 때 한 번 훑어보시면 저자가 무엇을 중요하게 생각하는지 엿볼 수 있슴다.
> [Week02] 이재원

- jaewon/Chapter.md
해당 장에서 토론할 거리를 조금 찾아보려고 한번 더 읽어봤는데, 짜달시리 눈에 띄는 내용은 없었습니다.
한가지 생각해보아야 할 점 정도는 찾아볼 수 있는데..
저자는 컨텍스트가 가지는 고질적인 문제점을 제시하고, 그에 대한 해결방안으로 컨텍스트 청크를 나누는 방법을 선택했습니다.
즉, 리랜더링 최적화를 위하여 전역으로 가지는 state별의 쌍만큼 context를 생성한 방식을 채택한 것인데, 저는 그다지 흥미를 느끼지 못했습니다. 자세한 내용은 노션에 정리해놓았습니다. 같이 읽어보면 좋을 듯 합니다. (__)
> [Week03] 이재원

- mogyeong/chapter03.md
Context는 당연히 전역 상태 관리를 위한 기능인줄 알았는데, 알고보니 Context의 초기 설계는 그 목적이 아니었고, 어찌 보면 내가 Context를 올바른 의도에 맞게 사용하지 않는 것이 아닌가하는 생각이 들었습니다.
그래서 시간이 부족해서 아직 찾아보진 않았지만 책의 3장 내용 이외에도 구글링해보면서 Context의 올바른 목적에 대해 찾아보면서 탐구해봐야겠고 느꼈습니다.
그리고 reduceRight라는 새로운 함수도 알게됐는데 이 함수도 앞으로 잘 활용해봐야겠습니다.
저는 Context를 평소에 잘 사용을 많이 안했었어서, 이 책에서의 Context에 대한 설명이 부족하다거나 의문점이 드는 내용이 있는지 잘 파악하기는 어려웠는데 다른 분들은 책의 내용에 대해 어떻게 느끼셨는지 궁금합니다.
> [Week03] 김모경

- jeongmin/Chapter3.md
저는 전역 상태 툴을 많이 사용해본 적이 없습니다.
옛날 옛적 회사에서 Redux + Toolkit 조합을 사용했던 것 외에, zustand 몇 군데 깔짝댄 것 되에 사용 해본 적이 없어서 보통 상태관리를 위해 Context를 사용하곤 했습니다.
Context values changes에 따라 하위 컴포넌트가 리랜더링 되는 문제 때문에 가능하면 비즈니스 로직과는 엮지 말아야 겠다는 생각을 해서 최근엔 사용을 주저하고 있습니다.
가능하면 Context는 작은 영역만을 묶어서 상태관리를 할 때, 혹은 디자인시스템 컴포넌트 내에서의 상태관리를 위한 용도로 주로 사용하고 있구요.
Context를 사용했을때 가장 큰 장점이 무엇이냐 생각해보면 `상태 영역 격리`인 듯 합니다.
예를들어 아래의 예시 코드는 FooOnlyProvider가 Foo 컴포넌트를 감싸고 있고, 이를 통해  Foo컴포넌트 하위에서 FooOnlyProvider에 정의된 상태값을 사용할 수 있다는 점을 알 수 있습니다. 그리고 Bar 컴포넌트에서 FooOnlyProvider에 정의된 상태값을 사용하려고 할 때는 정상동작 하지 않을 것이라는 점도 명시적으로 알 수 있습니다.
```JSX
<>
<FooOnlyProvider>
<Foo />
</ FooOnlyProvider>
<Bar />
</>
```
이렇듯 Context를 사용하면 상태가 사용될 수 있는 영역을 명확하게 구분해서 정의 해둘 수 있다는 점이 큰 장점으로 느껴집니다. 이로 인해 상태가 의도치 않게 변경되는 사이드이펙트를 미연에 방지 할 수 있습니다.
Redux외 다른 마이크로 상태 관리 …
> [Week03] 성정민

- gyuri/chapter3.md
context에 대해 깊이 알아볼 수 있었고 잘못 알고 있던 내용을 바로 잡을 수 있었습니다.
저는 컨텍스트를 사용하지 않는 컴포넌트는 리렌더링이 되지 않는 것으로 알고있었는데, 그렇게 할 수 있었던 이유가 memo로 감싸서 그런거였습니다. 부모 컴포넌트의 랜더링과 컨텍스트의 리랜더링의 차이에 대해 자세히 알 수 있어서 좋았고, 조금 복잡하지만 사용자 정의 훅과 팩토리 패턴, reduceRight으로 provider의 중첩을 막고 최적화 할 수 있는 방법에 대해 설명해 줘서 다음에 써봐야겠다는 생각이 들었습니다. 개발 하면서 많이 사용할 일은 없을 것 같지만, 제 경험상  많은 양의 정보를 단계적으로 표시해야하는 페이지에서 비슷한 고민을 한 적이 있어서 이 때 컨텍스트를 사용했으면 좀 더 최적화할 수 있지 않았나 싶습니다.
- 컨텍스트의 단점은 무엇일까?
> [Week03] 김규리

- jaewon/Chapter.md
이때까지 살펴봤던 내용 중 가장 재밌었던 챕터였습니다. 저자가 이때까지 걸어온 행보를 들여보다면 특정 라이브러리에 제한되지 않으며 그 라이브러리가 제공해주는 기능을 구현, 혹은 대체하는 것에 많은 노력을 기울였단 것을 알 수 있습니다. 그리고 이번 챕터에서 그 내용이 가장 두드러지게 나타납니다. 비단 redux를 어떻게 잘 사용할 수 있을까에 대해서만 고민을 해보았지 지금 저자가 글을 전개하는 것처럼 redux를 어떻게 대체할 수 있을까, 혹은 redux를 어떻게 구현할 수 있을까에 대한 고민은 해보지 않았던 것 같습니다.
돌이켜보면 React를 처음 배울 때 React에 익숙해지기 위해서 React-Router-Dom에서 제공해주는 기능들을 라이브러리를 사용하지 않고 react로 구현해보면서 학습했던 기억이 납니다. 어느정도 react에 익숙해진 이후에는 특정 기능이 필요할 때에, 그 기능을 제공해주는 라이브러리를 찾아 간단하게 사용법만 확인하고, 해당 라이브러리를 사용하면서 넘어갔었던 것 같습니다. 개인적으로 새로운 무엇인가를 배우고자 할 때, 그것을 뜯어보았는지. 단순히 그 기능을 제공해주는 라이브러리의 사용법만 익히고 넘어간 것은 아닌지 반성하게 되는 시간이었습니다.
> [Week04] 이재원

- mogyeong/chapter04.md
구독 패턴에 대해 조금이나마 친숙해져서 좋았습니다.
실무에서 구독 패턴을 많이 보진 못했는데, 찾아보려고 하니 최근 사례는 잘 안보였던 것 같습니다.
제가 못 발견한걸 수도 있는데, 구독 패턴을 잘 사용하지 않는 추세라면 그 이유가 있을지 궁금합니다.
> [Week04] 김모경

- gahee/chapter4
[Week04] 염가희
최근 Redux를 공부하고 있었는데..   이번 챕터를 읽으면서 나는 Redux를 공부한게 아니고 그저 사용법을 익혔왔더라는걸 깨달았습니다.. 
특히, useSelector와 같은 훅들을 사용할 때, 내부적인 동작 방식을 이해하지 못한 채 겉핥기 식으로 사용해왔다는 점이 가장 크게 다가왔고 너무 부끄러웠습니다. 
이번 학습에서 useSelector 훅의 동작 방식을 간략하게 나마 직접 구현해보면서, 그동안 제가 얼마나 표면적인 사용법에만 치중하고 있었는지 반성하는 계기가 되었습니당...
> [Week4] 염가희

- jeongmin/chapter4.md
리액트가 제공하지 않는 방법으로 외부에서 어떤식으로 상태를 관리할 수 있을지 감이 잡히던 챕터였습니다.
개인적으로 지금까지 읽어왔던게 이번 챕터의 이해를 위해서가 아니었나 싶은느낌으로 재미있게 읽었습니다.
현재 useSyncExternalStore를 이용해 localStorage의 상태를 싱크로나이징 하는 커스텀 훅을 사용하고 있었는데, 이번 계기로 원리를 좀 더 알 수 있게 되어 좋았습니다.
> [Week04] 성정민

- moonha/chapter-04.md
그동안 주로 도구를 다루는 방법만 익혀오다가, 직접 도구를 만들어보는 과정이 있어서 매우 신선하고 의미 있는 경험이었습니다. 단순히 기능을 사용하는 것을 넘어서, 그 기능이 어떻게 구현되는지를 배우면서 한층 깊은 이해를 할 수 있었습니다. 특히, 저자가 앞선 챕터들처럼 단계별로 기능을 차근차근 추가하며 설명해 주는 방식이 복잡한 개념도 자연스럽게 받아들일 수 있도록 도와주었습니다. 이러한 설명 방식 덕분에 이 책이 더 매력적으로 느껴졌습니다.
> [Week04] 박문하

- gyuri/chapter4.md
그동안 구독 기능이 필요하면 라이브러리를 사용했고 직접 모듈을 만들어본적이 없어서 이번 장이 흥미로웠습니다. 저에게는 예제가 다소 이해하기 어려웠는데 (다소 부자연스러운 느낌이 있어서) 다 읽고보니 구독 구현에 대한 원리를 스텝 바이 스텝으로 설명하기 위해서인 것 같습니다. 예제 코드 외에도 react에서 useSubscription 코드를 어떻게 작성했는지 봐도 좋을 것 같아요. 확인해보니 useSubscription은 useSyncExternalStore를 이용한거라 useSyncExternalStore 코드를 가져와봤습니다.
https://www.npmjs.com/package/use-sync-external-store](https://github.com/facebook/react/tree/main/packages/use-sync-external-store/src)
> [Week04] 김규리

- jaewon/Chapter.md
이번 챕터에 제목은 거창하지만 실은, 2주차부터 4주차까지 학습한 내용을 모두 합쳐서 "구독상태의 컨텍스트 생성"이 주요한 내용이었습니다. 조금 심도 있게 살펴보아야 할 부분을 굳이 꼽자면 Context에 값을 접근하는 useSelector를 정의하는 파트를 꼽아볼 수 있을텐데, 사실 react-redux의 useSelector 동작에 대한 이해를 공고히 했다면 크게 어려운 부분이 없었으리라 판단됩니다. 차주 부터는 전역 상태 관리 라이브러리에 들어갑니다. 자주 사용해본 라이브러리도 있고, 아닌 라이브러리도 있는데 새로운 내용으로 학습해보길 기대합니다.
> [Week05] 이재원

- mogyeong/chapter03.md
- mogyeong/chapter04.md
- mogyeong/chapter05.md
가볍게 읽기 좋은 내용이었습니다.
컨텍스트(Context)와 구독 패턴을 함께 사용하여 전역 상태 관리의 단점을 극복한 사례로 Recoil, Zustand 등 라이브러리에서 활용되고 있다고 들었는데, 이러한 라이브러리를 직접 사용해보면서 더 깊게 이해해보면 좋을 듯 합니다.
> [Week05] 김모경

- wonjun/chapter-4.md
> [Week04] 이원준

- wonjun/chapter-5.md
[Week00] 이름
ex) [Week01] 김규리
이번에는 생각보다 쉬웠습니다! 뭔가 바로 사용 가능한 간단한 라이브러리를 만들 수 있어서 좋았어요.
> [Week05] 이원준

- gahee/chapter5.md
지난 챕터에서 글쓴이가 설명한 모듈 상태의 한계로 모듈과 Context API를 같이 사용하는 방법에 대한 챕터 였습니다. 
따로 자세히 쓸만한건 없지만, 그냥 그렇구나~ 하고 넘어갈 수 있는 부분이였네용
> [Week05] 염가희

- moonha/chapter-05.md
지금까지 배운 내용을 총 정리하는 챕터여서 지금까지 배운 내용을 복습할 수 있었습니다. 
[P.103]
- 컨텍스트를 언제 사용해야 하는지?
- 컨텍스트에 적절한 기본값을 설정하는 것은 중요
- 컨텍스트 공급자는 기본 컨텍스트 값 또는 부모 공급자가 제공하는 값이 있는 경우 이 값을 재정의(override)하는 메서드라고 볼 수 있음
- 적절한 기본값이 있다면 공급자를 사용할 이유가 없지만, 전체 컴포넌트 트리의 하위 트리에 대해 다른 값을 제공할 필요가 있다면 공급자를 사용해야 함
→ 이전 챕터에서도 궁금했는데, 일반적으로 ‘Provider의 사용은 해당 범위 내에서 컨텍스트 값을 사용하겠다.’ 고 명시하는 것이라고 생각합니다. 그래서 일부러 Context에 기본값을 사용하지 않는 편인데, Context를 Provider 없이도 사용하시는지 궁금증이 생겼습니다,
ex) 
```
function useCounterState() {
const value = useContext(CounterContext);
if (value === undefined) {
throw new Error('useCounterState should be used within CounterProvider');
}
return value;
}
```
> [Week05] 박문하

- gyuri/chapter5.md
앞으로 살펴보게 될 Zustand, Jotai  등의 전역 상태 라이브러리의 원리를 떠먹여주는 듯한 느낌을 받았습니다. 내용 자체는 4장의 이어져서 이해하기 어렵지 않았습니다.
동료에게 어떤 경우에 책에서 소개한 대로 useContext+useSubscription 조합을 사용할 것 같냐고 물었는데 그냥 전역 상태 관리 라이브러리르 쓰는게 나을 것 같다고 하셨습니다😅 저도 어느정도 공감 가는 바...
> [Week05] 김규리

- jaewon/Chapter.md
개인적으로 설명을 위한 설명, 개념을 위한 새로운 개념 정립(혹은 소개)이 많았던 단락이라고 생각합니다. 개인적으론 선호하지 않습니다. 조금 긍정적인 시각으로 살펴보면 "전역 상태"라는 것을 "어떻게 접근해야 하는가?" 라는 물음 아래에서 다양한 시도와 아이디어를 제시하는 것과 함께 장/단점을 소개한 단락이었습니다. 이후 라이브러리를 소개해주는 챕터들에서 해당 시각에 대한 피드백 혹은 단점의 극복등이 소개될 것이라 예상할 수 있습니다. 단, 그 과정이 기존 라이브러리의 selector에 대한 소개 그 이상 그 이하도 아니어서 아쉬움이 남지 않았나 싶습니다. 
5주차에 많은 이야기를 나누지 못해 마음이 무겁습니다. 6주차에도 이야기거리를 준비하지 못해 더 무겁네요. 차주 화요일까지 고민해볼 거리가 있을지 더 생각해보고 description을 추가하도록 하겠습니다.
> [Week06] 이재원

- jeongmin/Chapter6.md
이번 장을 완벽하기 이해하기에는 아직 설명이 충분치 않았다.
저자 특유의 바텀업 빌드를 새로 시작하는 것 같은데 또 어떤 놀랄만한 아이디어를 알려줄지 기대가 된다.
추가적으로 다이토 카시가 만든 react-tracked 라이브러리에 대한 짧은 소개가 나왔는데, 리액트 컴파일러가 탄생한 이상 미래엔 저자가 소개하려고 하는 내용이 오히려 안티 패턴이 되지 않을까 하는 우려가 든다. 
https://x.com/dai_shi/status/1763701256105922719?s=46&t=vGw10bf-g_KuhOx-c6SWHw
(저자의 트위터에도 이에 대한 우려가 있다.)
> [Week06] 성정민

- sehee/Chapter7.md
요즘 많이 쓰인다는 사실만 알고 있던 Zustand를 이전 챕터에서 배워왔던 상태관리의 시스템적 측면에서 분석하고 공부할 수 있어서 좋았습니다.
앞장의 내용들이 무엇을 위한 건지 감이 안 왔었는데, 앞으로 다룰 상태관리 라이브러리들의 메커니즘을 설명한 거였구나~ 하는 깨달음을 얻는 챕터였습니다.
그리고 셀렉터 함수로 새로운 객체를 반환하는 패턴... 엄청 많이 썼었는데... 잘못 사용하고 있었다는 걸 이번 계기로 알게 되었습니다. 🥲
> [Week07] 김세희

- jaewon/Chapter.md
[저번주에 느낀점](https://github.com/JAVACAFE-STUDY/2024-msmrh-study/pull/57)으로 query-cache의 개념이 등장한 이후로부터는 프론트엔드에서 "전역 상태"의 비중이 많이 줄었다고 생각하기에, '전역 상태 라이브러리를 어떻게 사용하냐?' 보다 '어떤 데이터를 전역 상태로 관리할 것인가?'에 더 방점을 찍게 되는 것 같다고 공유드린 바 있습니다. 그런의미에서 이번주를 포함한 10주차까지의 내용은 큰 흥미를 느끼지 못할 것 같았지만 Jotai의 동작방식은 흥미로웠습니다.
사실 어떠한 global management tool을 사용하든 목표한 바만 이룰 수 있다면 어떠한 도구든 상관없다고 생각합니다. 그런 의미에서 도구의 선택은 러닝커브 혹은 그 도구에 익숙한 개발자의 유무 정도로 귀결된다고도 생각했는데 Jotai는 꽤나 강력한 기능들이 같이 구현되어 있다는 느낌을 받았네요. 역시 만족도가 1등인 건 이유가 있나 봅니다. 시사하는 바를 책이 아닌 공식문서에 느꼈단건 좀 안타깝네요. 이 책은 설명을 위한 설명이나 개념을 창시하고 설명하는 파트가 필요이상으로 많은 것 같습니다.
> [Week08] 이재원

- mogyeong/chapter08.md
8장 내용을 통해 jotai 사용법에 대해 처음으로 접해봤는데 사용하기 쉽고 강력한 라이브러리라고 느껴졌습니다.
무엇보다 atom이 atom을 포함할 수 있고 atom으로 관리되는 상태들이 상향식 접근으로 확장 가능하다는 점과,
Recoil과 다르게 Jotai에서는 selector가 없이도 atom 값에서 또 다른 파생된 상태를 만들 수 있다는 점이 인상 깊었습니다.
아직은 구글에 'jotai' 라고만 검색했을 때 다른 상태 관리 라이브러리에 비해 검색 결과가 적긴 하네요
팀에 도입하고 싶다면 먼저 개인 프로젝트로 사용을 많이 해보고 나서 생각해봐야겠습니다. ㅎㅎ
> [Week08] 김모경

- moonha/chapter-08.md
회사에서 Jotai를 사용하고 있는데, 조금 잘못된 방향으로 활용하고 있었다는 생각이 들어서 반성하게 되었습니다. 
책에는 다루어지지 않았지만, 공식 문서에 유용한 기능들이 많이 있어서 공식 문서를 한 번 제대로 공부해보고 어떻게 응용할 수 있을지 더 고민해봐야겠다고 생각하였습니다.
> [Week08] 박문하

- sehee/Chapter8.md
리덕스와 확실히 다른 스타일인 Jotai 라이브러리의 개념에 대해서 알게 되었습니다. 리덕스만 쓰던 입장에서 Jotai를 보니 굉장히 좋고 간편해 보였습니다. 한번 활용해 보고 싶은 라이브러리였습니다.
혹시 Jotai를 써보신 분이 계시다면 어떤 단점이나 불편한 점이 있는지 궁금합니다.
> [Week08] 김세희

- saemi/chapter9.md
책에서 언급한 내용으로 보자면, valtio를 쓰는 이점보다 리액트와 멘탈모델이 다르다는 단점이 너무 명확한 듯하여 
실제로 valtio가 리액트와 궁합이 좋은지, valtio를 쓴다면 어떤 근거로 해당 기술을 도입했을지 궁금합니다.
구글링해 보면 실제로 도입한 사례는 찾기 힘드네요..
> [Week09] 이새미

- jaewon/Chapter.md
에상 질문의 예상 답변 : ㄴㄴ
나도 궁금해서 찾아본 내용 : 
답변. [mobX에서 Proxy에 대한 지원](https://mobx.js.org/configuration.html#proxy-support)이 되는걸로 알고 있음.. 저번 장에서 배운 Jotai에서도 immer를 지원하고 immer도 기본적으로 Proxy 구현체. 이 [게시글](https://medium.com/dailyjs/how-to-use-javascript-proxies-for-fun-and-profit-365579d4a9f8)을 보면 API 모니터링으로도 활용할 수 있다고 하네요. 자주 사용되냐고 묻는다면 적어도 전 많이 사용 안한 것 같슴다. 아직 ECMAScript 신기능들은 조금 어색하네요,
저자의 방식에서는 createTodo 나 removeTodo 와 같은 메서드들이 proxy 객체와 무관하게(예제 코드에선 전역으로) 설정되어 있는데 응집도 측면에서 새로운 관리 포인트만 생성하는 것 같습니다.  valtio 공식문서를 살펴보면 [class를 지원](https://valtio.dev/docs/api/basic/proxy)해주는 것도 확인할 수 있기에 아래처럼 proxy 를 선언하는 것이 좋을 것 같습니다. 혹은 [proxyset](https://valtio.dev/docs/api/utils/proxySet)도 괜찮은 선택지 같네요.
```javascript
class Todo {
todo: TodoItem[] = [];
createTodo = (title: string) => {
this.todo.push({
id: …
```
>  [Week09] 이재원

- jeongmin/Chapter9.md
> [Week09] 성정민

- sehee/Chapter9.md
Valtio는 처음 들어보는 라이브러리였는데, Proxy라고 하는 자바스크립트 내장 객체를 활용하여 상태변화를 감지하고 리렌더링 최적화를 한다는 디자인 모델이 신기하고 인상적이었습니다.
예시 코드를 보니 확실히 Zustand보다 코드 양도 적게 나오고 간편한데, 왜 다른 라이브러리에 비해 인지도가 낮은 걸까 하는 의문이 들었습니다. 써보신 적 있는 분이 계시다면 후기가 궁금합니다!
> [Week09] 김세희

- mogyeong/chapter09.md
Valtio 라이브러리 사용법과 더불어서 Proxy에 대해서도 접해볼 수 있게 돼서 좋았습니다.
리액트에서 이 내용들을 어떻게 잘 활용해볼지는 더 알아봐야할 듯 합니다 ㅎㅎ
Valtio에 내부적으로 사용되는 proxy-compare 라이브러리 내부 소스코드에서 자동 렌더링 최적화 로직이 있는 코드는 [여기](https://github.com/dai-shi/proxy-compare/blob/main/src/index.ts#L298) 인데, 저도 아직 대충 봤지만 참고사항으로 공유 드립니다~
> [Week09] 김모경

- jaewon/Chapter.md
느낀 점을 조금만 길게 적으면 본문보다 길게 적을 수 있을 것 같습니다. 이번주 발표가 걸리지 않기를 바라야겠습니다.
이전 PR에서 반복하여 말했듯이 7장에서 부터 이 책에 대한 흥미가 급속도로 떨어졌습니다. 쪽수로 따지면 80쪽, 책의 1/3 분량인데 애석하기 그지 없습니다. 그럼에도 느낀점을 조금 끼적여보자면.. React Tracked는 앞선 세 라이브러리와는 성격이 조금 달랐습니다. 앞의 챕터 역시 라이브러리를 구성하는 방식과 로직에 대한 설명이 아닌 사용법을 설명하긴 했지만 그럼에도 불구하고 전역 상태의 대체제로 제시되었지만, 이번 챕터에서 소개한 React Tracked는 기존의 전역 상태에서 리랜더링 최적화만을 위해 도입된 훅 그 이상 그 이하도 아니었습니다.
단순한 라이브러리 사용법만 열거하는 비판점을 떠나서 이 라이브러리가 필요한가? 라는 의문을 감출 수 없습니다. 요즘의 프론트엔드 환경에서 대형 프로젝트를 관리할 때에 초기 로드 속도를 위해서 외부 패키지를 사용하는 것이 아니라 자체 개발을 해나가는 환경이라 더더욱이 공감을 하지 못한 것 같습니다. 그럼에도 불구하고 조금 의의를 찾아보자면.. context의 한계점을 지적하고 그것을 극복해나갈 수 있는 방향성을 제시했다는 점을 들 수 있을 것 같습니다. "향후 전망" 챕터에서 밝혔듯이 React Context 내부 로직을 통해 보다 쉽게 리랜더링 최적화를 제안해줄 수 있다면 더 생산적인 방향으로 발전해나감은 부정할 수 없을 것 같습니다.
> [Week10] 이재원

- moonha/chapter-10.md
그동안 이 책이 주로 상태 관리에 대한 설명에 집중해왔는데, 갑자기 리렌더링 최적화를 위한 라이브러리를 소개해서 다소 의아했습니다. 하지만 컨텍스트의 단점인 리렌더링 문제를 보완할 수 있는 라이브러리라는 점에서 흥미로웠습니다. 다만, 분량 때문인지 내부 구현에 대한 구체적인 설명 없이 특정 라이브러리를 활용했다는 정도로만 언급된 점은 아쉬웠습니다.
만약 리액트에 정식으로 도입된다면, 그동안 컨텍스트의 리렌더링 최적화 문제로 인해 호불호가 갈렸던 부분이 해결되어 외부 라이브러리에 대한 의존성을 줄일 수 있을 것이라는 기대감이 생깁니다. 앞으로의 동향을 주의 깊게 지켜봐야 할 것 같습니다.
> [Week10] 박문하

- jeongmin/Chapter10.md
- jeongmin/Chapter9.md
React Tracked의 사용법에 대해서 설명을 하고 있지, 실제로 어떻게 프록시를 활용해 상태 사용 추적을 할 수 있는지 근원적인 코드는 설명이 되어있지 않았다. 활용장이 대부분 마찬가지인데, 이런식으로 겉핥기 방식의 사용법만 나열 해둘거면 굳이 왜 추가했는지 의문일 따름이다.
어디에다 사용 해야하는 라이브러리일지 명쾌하게 떠오르진 않지만, 당장의 사용법을 생각해보면 context내에 많은 로직이 얽혀있는 레거시 앱에 저적용할 경우 성능적인 이득이 있을 듯 하다
> [Week10] 성정민

- gahee/chapter10.md
다른 분들 느낀점을 읽어보니, 다들 비슷한 생각을 가지고 게신듯합니다. 사실 한챕터가 남았지만.. 작가가 만든 라이브러리를 소개하는 책. 그 이상 이하도 아닌것 같다는 생각이 들었습니다. ㅠㅠ.. 
공식문서가 책보다 더 가독성이 좋은건 저만 느낀걸까요..?
> [Week10] 염가희

- saemi/chapter10.md
전역 상태 관리 도구나 Context를 많이 사용해 본 경험이 없어 React Tracked의 리렌더링 최적화와 코드 간결성 측면에서 얼마나 유리하고 효율적인지에 대해 크게 와닿지 않습니다. 그래도 상태 사용 추적이라는 명확한 목적을 가지고 특정 상태 관리 도구에 종속되지 않으면서도 유연하게 적용할 수 있다는 점은 장점으로 느껴졌습니다. 다른 분들처럼 저 역시 React Tracked가 내부적으로 어떤 방식으로 구현되었는지 궁금합니다.
> [Week10] 이새미

- mogyeong/chapter10.md
상태 전파 기능 없이 리렌더링 최적화 만을 위한 용도이다 보니 이전의 Valtio보다도 react-tracked 사용 사례가 찾기 힘들긴 하네요 ㅎ
Context의 단점을 보완해주긴 하지만 잘못 사용하면 라이브러리 사용을 위한 라이브러리가 될 수도 있을 듯 합니다.
저자가 바라는 것처럼 향후 리액트가 `useContexSelector`를 공식적으로 제공할지 궁금해지네요 ㅎㅎ
> [Week10] 김모경

- sehee/Chapter10.md
[Week00] 이름
ex) [Week01] 김규리
이 책을 읽으면서 항상 느끼지만, 저자가 소개하는 모든 라이브러리가 내겐 다 매력적으로 느껴진다. React Tracked도 그렇다. useContext에서 리렌더링 문제 때문에 다른 라이브러리로 마이그레이션할 계획이 있는 경우에 유용할 것 같다. 지금까지 나온 라이브러리들 중 일단 가장 호환이 좋아 보인다. Redux와 같이 사용할 경우에도, useSelector 사용 시의 번거로움을 많이 줄여줄 수 있을 것 같았다.
새롭게 상태관리 라이브러리를 선택한다면 다른 것들을 먼저 고안해 보겠지만, useContext로 많이 사용된 서비스를 보완하고자 할 때 고려하기 좋은 라이브러리라고 생각됐다.
> [Week10] 김세희

- sehee/Chapter11.md
이번 주차는 읽기만 하고 정리를 못했습니다,, 😭 벌금 차감하겠습니다.
Redux와 Zustand의 차이는 예전에 Zustand 챕터 진행하다가 궁금해져서 찾아보기도 했었는데, 따로 짚어 설명해 줘서 좋았다. MobX도 어떻게 쓰이는지 간략하게 훑어볼 수 있어 좋았다.
그리고 생각보다 앞 내용들이 기억나지 않아서... 다 읽고 내용을 한 번 크게 정리하는 시간을 가져야 할 것 같다.
처음 리액트훅 상태관리 책을 샀던 이유는 최근 상태관리 메커니즘들에 대한 팔로업을 하고 싶어서였다.
리덕스 이후로 수많은 상태관리 라이브러리들이 등장하고 있다는 사실과 그 사용율이 점점 증가하고 있다는 소식은 들어 알고 있었지만, 실제로 접할 일이 없다 보니 공부하질 못했다. 그래서 항상 ‘언젠가 찾아봐야지…’ 생각만 달고 있었다.
그러던 중 yes24 신작 코너에서 이 책을 발견했는데, 많이 들어 본 라이브러리 이름들이 잔뜩 박힌 목차를 발견하고 바로 사 버렸다. 그 상태로 책을 몇개월간 방치하다가…. 스터디 모집글을 발견하고 ‘이거다’ 싶어서 신청했다.
그래서 내가 기대했던 점은 : **리덕스 말고 다른 상태관리 라이브러리 툴들이 어떻게 다른지, 어떤 원리로 돌아가는지 이해하기**였다**.** 그리고 기본적인 사용법도 알려줬으면.
결과적으로 이 목표는 완전히 채워졌다. 
기본 목표였던 상태관리 라이브러리들에 대한 이해도가 조금은 높아졌다.
프론트엔드 생태계에 새로운 핫한 라이브러리가 떠오르면, 항상 ‘이게 왜 등장했지?’ 가 먼저 궁금하곤 했다. 이 라이브러리가 기존의 어떤 문제를 풀어주길래 이렇게 트렌드가 옮겨지는 건지, …
> [Week11] 김세희

- moonha/chapter-11.md
그동안 사용법에만 초점을 맞춰 공부했다면, 이번 스터디를 통해 동작 원리에도 더 깊이 생각할 수 있게 되어 처음 기대했던 목표를 어느 정도 달성할 수 있었습니다. 특히, 혼자 공부했다면 절대 완독하지 못했을 것 같은 책을 스터디 덕분에 끝까지 읽을 수 있었다고 생각합니다. 
전역 상태 관리 라이브러리가 어떻게 동작하는지 그 원리에 대해 깊이 생각하고 학습할 수 있었습니다. 또한, 이러한 원리를 실무에서도 적극적으로 응용해봐야겠다는 깨달음을 얻었습니다.
도전과 어려움은 없었고, 휴가로 인해 2주간 자리를 비워 출석률 100%를 달성하지 못한 점이 개인적으로 아쉬움으로 남습니다.
전반부의 라이브러리 동작 원리를 이해하고 직접 구현해보는 과정이 인상 깊었습니다. 다만, 후반부의 라이브러리를 다소 겉핥기 식으로 다룬 부분은 굳이 이 정도 분량을 할애할 필요가 있었는지 의문이 들었습니다.
얇은 책의 경우 주제별로 묶어 더 압축적으로 진행한 뒤, 책 외의 부가적인 내용을 학습할 시간을 가졌더라면 어땠을까 하는 생각도 듭니다
사내 스터디를 제외하고는 처음으로 제대로 된 스터디를 경험해봤습니다. 비슷한 경력을 가진 같은 직군의 개발자들과 이야기를 나눌 수 있어서 유익하고 즐거운 시간이었습니다. 마지막까지 함께할 수 있어 감사했습니다.
> [Week11] 박문하

- mogyeong/chapter11.md
1. 스터디를 통해 목표 및 기대를 채울 수 있었는지 
‘리액트를 다루는 기술’ 이후에 리액트에 대한 책을 완독한건 이번이 처음이었습니다. 스터디 모임이라는 제한 사항이 없었다면 “완독”을 하지는 못하고 그 때 그 때 필요한 부분에 대해서만 책에서 찾아봤을 것 같아요. 아래 4번에 적은 내용처럼 책에 대해서 아쉬운 부분이 있기도 했지만, 업무 외에 공부하는 습관을 갖게 된 부분은 목표를 달성했다고 보고 있습니다. 그치만 아직 많이 부족하고 다른 분들 보면서 더 많이 성장하고 경험해봐야겠다는 생각을 했습니다. 
2. 얻은 성과와 배운점
리액트 상태 관리에 대한 책을 통해 얻은 지식들도 물론 유익한 경험이였지만, 퇴근하고나서 공부를 하는 습관을 갖게 된 부분이 가장 큰 성과였습니다. 
6. 도전과 어려움이 있었다면 어떻게 극복했는지 
아무래도 1번만 준비가 안돼도 2만원씩이나 벌금이 깎이다 보니 의자에 앉아서 책을 볼 수 밖에 없었어요ㅎㅎ 
4. 책에 대한 평가 
예제를 위한 예제가 많았기도 하고 단순 개념 설명에 대해서는 책 내용보다 공식문서가 보기 편했던 점은 있었습니다. 그래도 평소처럼 공식문서만 보는데에서 그쳤다면 책에서 설명한 라이브러리를 직접 구현한다거나 내부 구현 의도를 파악하는 식의 학습은 하지 않았을 거라 생각이 돼서 이 책에 대해서는 만족하고 있습니다. 
5. 다음 스터디를 위해 개선할 점 
책 내용에 나아가서 다른 인사이트를 찾는 시간을 더 가져야겠다는 생각을 했습니다. 
9. 전체적인 소감 
야근이 가끔씩 있어서 완주할 수 있을까 불안했지만 다행히 스터디 같이 완주할 수 있었네요 ㅎㅎ; …
> [Week11] 김모경

- jaewon/Chapter.md
위 질문에 앞서 목표를 먼저 되돌아보겠습니다. 이제 5년 정도 가까이 개발자 일을 진행하고 있는데, 일을 하는 동안 스터디, 사이드 프로젝트와 같은 외부 사람들과의 활동을 진행해본 적이 없습니다. 새로운 인풋이 없다면 변화가 없기에 이번 자바카페를 통해 첫번째 스터디를 진행했습니다. 뭔가 우여곡절이 많을 줄 알았는데, 생각보다 무난하게 스터디를 끝까지 참여한 것 같습니다. 신세 많이졌습니다. (__)
이때까지 기능 구현을 위한 라이브러리를 도입할 때 "어떤 라이브러리르 선택할 것인가?" 에 대해 깊이 고찰했다곤 말 못할 것 같습니다. weekly download 횟수 정도만 간단하게 살펴본 것 같습니다. 이번 스터디를 통해 추후 전역 객체를 사용할 필요가 있을 때 프로젝트의 성격에 맞는 라이브러리를 선택할 수 있는 선구안을 얻은 것 같습니다. 물론, 요즘의 프론트엔드에서는 대체될 수 있는 다양한 방법이 있기에 전역객체의 도입이 필수라고는 생각하지 않습니다. 그럼애도 대체되는 방법이 어렵거나 추가적인 컨벤션을 요구한다면 이 책이 내용이 생각날 것 같습니다. 
믿거나 말거나 저는 낯을 많이 가립니다. 친해지면 괜찮은데, 친한데 낯을 가리는 사람이 어디있겠습니까? 고리타분한 변명입니다. 예전에는 소심해서 낯을 많이 가린다고도 표현도 못했습니다. 이거 극복하려고 에버랜드에서 알바도 해보고, 강사생활도 해봤는데 잘 안되더군요. 사람이 타고나는 성격이 있는 것 같습니다. 예전부터 사람들과 활발히 교류해야하는 순간이 오면 연기를 하는 편입니다. 진심을 속이고 가면을 쓴다는 느낌과는 다릅니다. 적어도 "이 순간 만큼은 나 …
> [Week11] 이재원
